version: '3.1'
services :
  db:
    image: postgres:10-alpine
    container_name: db-todo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_DB: dbtodo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080